# Generated by Django 4.0.6 on 2022-07-27 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='category_type',
        ),
    ]
