# Generated by Django 4.0.6 on 2022-07-25 19:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_alter_product_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='img',
            field=models.ImageField(default=1, upload_to='userProfileImages'),
            preserve_default=False,
        ),
    ]
