# Generated by Django 4.0.6 on 2022-07-28 14:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0003_order_user_alter_order_trading_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trading_price',
            field=models.IntegerField(max_length=10),
        ),
    ]
