# Generated by Django 4.0.6 on 2022-07-28 14:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main_app', '0004_alter_order_trading_price'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='trading_price',
            field=models.FloatField(max_length=20),
        ),
    ]
